# Generated by Django 5.1.7 on 2025-04-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('puntos_exp', models.PositiveIntegerField(default=0)),
                ('puntos_honor', models.PositiveIntegerField(default=0)),
                ('xp_siguiente_nivel', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
