# Generated by Django 5.1.7 on 2025-04-02 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(help_text='Clase de icono de FontAwesome', max_length=50)),
                ('tiene_rangos', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(help_text='Clase de icono de FontAwesome', max_length=50)),
                ('puntos_honor', models.PositiveIntegerField(default=0)),
                ('puntos_exp', models.PositiveIntegerField(default=0)),
                ('requisito_nivel', models.PositiveIntegerField(default=0)),
                ('es_secreto', models.BooleanField(default=False)),
                ('es_raro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.AlterModelOptions(
            name='create_subs',
            options={'verbose_name': 'Sublíder', 'verbose_name_plural': 'Sublíderes'},
        ),
        migrations.AddField(
            model_name='create_subs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='create_subs',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del equipo o grupo', null=True),
        ),
        migrations.AddField(
            model_name='create_subs',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='create_subs',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre ti', null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='juego_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='show_discord',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createuser',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='streaming_enabled',
            field=models.BooleanField(default=False, help_text='¿Haces streaming de tus partidas?'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='twitch_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='actividad_semanal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dias_en_clan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(choices=[('ALL_ROUNDER', 'Todoterreno'), ('STRATEGIST', 'Estratega'), ('SUPPORT', 'Soporte'), ('FRAGGER', 'Fragger'), ('SNIPER', 'Francotirador'), ('LEADER', 'Líder'), ('SPEEDRUNNER', 'Speedrunner'), ('COLLECTOR', 'Coleccionista')], default='ALL_ROUNDER', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_actividad',
            field=models.CharField(choices=[('ONLINE', 'En línea'), ('AWAY', 'Ausente'), ('BUSY', 'Ocupado'), ('OFFLINE', 'Desconectado')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='eventos_asistidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_ultimo_ascenso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mensaje_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='misiones_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('RECRUIT', 'Recluta'), ('MEMBER', 'Miembro'), ('VETERAN', 'Veterano'), ('ELITE', 'Élite'), ('MASTER', 'Maestro'), ('LEGEND', 'Leyenda')], default='RECRUIT', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol_especial',
            field=models.CharField(choices=[('NONE', 'Ninguno'), ('SUBLEADER', 'Sublíder'), ('CAPTAIN', 'Capitán de Equipo'), ('TRAINER', 'Entrenador'), ('EVENT_MANAGER', 'Gestor de Eventos'), ('CONTENT_CREATOR', 'Creador de Contenido')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='torneos_ganados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='torneos_participados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('premios', models.TextField(blank=True, null=True)),
                ('xp_participacion', models.PositiveIntegerField(default=50)),
                ('honor_ganador', models.PositiveIntegerField(default=100)),
                ('organizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_participados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEVEL_UP', 'Subida de Nivel'), ('RANK_UP', 'Promoción de Rango'), ('ACHIEVEMENT', 'Logro Desbloqueado'), ('EVENT', 'Evento Próximo'), ('ADMIN', 'Mensaje Administrativo'), ('TEAM', 'Mensaje de Equipo')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'unique_together': {('user', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='PerfilJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_juego', models.CharField(blank=True, max_length=50, null=True)),
                ('horas_jugadas', models.PositiveIntegerField(default=0)),
                ('personaje_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_juego', models.PositiveIntegerField(default=1)),
                ('id_jugador', models.CharField(blank=True, help_text='ID o username dentro del juego', max_length=100, null=True)),
                ('es_juego_principal', models.BooleanField(default=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_juego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Juego',
                'verbose_name_plural': 'Perfiles de Juego',
                'unique_together': {('user', 'juego')},
            },
        ),
    ]
