# Generated by Django 5.1.7 on 2025-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_juego_logro_alter_create_subs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(choices=[('ALL_ROUNDER', 'Todoterreno'), ('STRATEGIST', 'Estratega'), ('SUPPORT', 'Soporte'), ('FRAGGER', 'Fragger'), ('SNIPER', 'Francotirador'), ('LEADER', 'Líder'), ('SPEEDRUNNER', 'Speedrunner'), ('COLLECTOR', 'Coleccionista')], default='Todoterreno', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('RECRUIT', 'Recluta'), ('MEMBER', 'Miembro'), ('VETERAN', 'Veterano'), ('ELITE', 'Élite'), ('MASTER', 'Maestro'), ('LEGEND', 'Leyenda')], default='Recluta', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol_especial',
            field=models.CharField(choices=[('NONE', 'Ninguno'), ('SUBLEADER', 'Sublíder'), ('CAPTAIN', 'Capitán de Equipo'), ('TRAINER', 'Entrenador'), ('EVENT_MANAGER', 'Gestor de Eventos'), ('CONTENT_CREATOR', 'Creador de Contenido')], default='Ninguno', max_length=20),
        ),
    ]
