# Generated by Django 5.1.7 on 2025-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_createuser_celular_alter_perfil_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
