# Generated by Django 5.1.7 on 2025-04-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_createuser_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(help_text='Clase de icono de FontAwesome', max_length=50)),
                ('puntos_honor', models.PositiveIntegerField(default=0)),
                ('puntos_exp', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rango',
                'verbose_name_plural': 'Rangos',
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol_especial',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('NONE', 'Ninguno'), ('SUBLEADER', 'Sublíder'), ('CAPTAIN', 'Capitán de Equipo'), ('TRAINER', 'Entrenador'), ('EVENT_MANAGER', 'Gestor de Eventos'), ('CONTENT_CREATOR', 'Creador de Contenido'), ('MODERATOR', 'Moderador'), ('AMATEUR', 'Cahorro')], default='Ninguno', max_length=20),
        ),
        migrations.CreateModel(
            name='RangoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rango')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rango de Usuario',
                'verbose_name_plural': 'Rangos de Usuarios',
            },
        ),
    ]
