# Generated by Django 5.1.7 on 2025-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rango_alter_perfil_rol_especial_rangousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(choices=[('R', 'Todoterreno'), ('STRATEGIST', 'Estratega'), ('SUPPORT', 'Soporte'), ('FRAGGER', 'Fragger'), ('SNIPER', 'Francotirador'), ('LEADER', 'Líder'), ('SPEEDRUNNER', 'Speedrunner'), ('COLLECTOR', 'Coleccionista')], default='Todoterreno', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('RECLUTA', 'Recluta'), ('MEMBER', 'Miembro'), ('VETERAN', 'Veterano'), ('ELITE', 'Élite'), ('MASTER', 'Maestro'), ('LEGEND', 'Leyenda')], default='Recluta', max_length=20),
        ),
    ]
