# Generated by Django 5.1.7 on 2025-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_perfil_especialidad_alter_perfil_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='lv_audi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
