# Generated by Django 5.1.7 on 2025-07-23 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('otro', 'Otro')], max_length=10)),
                ('urgencia', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado')], default='borrador', max_length=10)),
                ('firma_digital', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SAR',
                'verbose_name_plural': 'SARs',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('tiempo_respuesta', models.IntegerField(help_text='Minutos')),
                ('tiempo_resolucion', models.IntegerField(help_text='Horas')),
                ('metricas', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('complejidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=10)),
                ('sar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ger.sar')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='ger.usuario')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_implementacion', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('repositorio', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado_pruebas', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('parcial', 'Parcial')], max_length=10)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solucion', to='ger.ticket')),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cumplimiento', models.CharField(choices=[('cumplido', 'Cumplido'), ('incumplido', 'Incumplido'), ('parcial', 'Parcial')], default='cumplido', max_length=10)),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ger.sla')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ger.ticket')),
            ],
            options={
                'verbose_name': 'Relación Ticket-SLA',
                'verbose_name_plural': 'Relaciones Ticket-SLA',
                'unique_together': {('ticket', 'sla')},
            },
        ),
        migrations.AddField(
            model_name='sla',
            name='tickets',
            field=models.ManyToManyField(related_name='slas', through='ger.TicketSLA', to='ger.ticket'),
        ),
        migrations.AddField(
            model_name='sar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sars', to='ger.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('sistema', 'Sistema')], max_length=10)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido'), ('leido', 'Leído'), ('fallido', 'Fallido')], default='enviado', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ger.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('tamano', models.IntegerField(help_text='Tamaño en bytes')),
                ('hash_archivo', models.CharField(help_text='SHA-256', max_length=64)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ruta_almacenamiento', models.CharField(max_length=255)),
                ('sar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ger.sar')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'indexes': [models.Index(fields=['tipo'], name='ger_documen_tipo_67ded3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='ger.ticket')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'indexes': [models.Index(fields=['fecha'], name='ger_auditor_fecha_48483a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='ger_ticket_priorid_eeea62_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='ger_ticket_estado_4a01dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sar',
            index=models.Index(fields=['estado'], name='ger_sar_estado_abf436_idx'),
        ),
        migrations.AddIndex(
            model_name='sar',
            index=models.Index(fields=['urgencia'], name='ger_sar_urgenci_98a435_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_envio'], name='ger_notific_fecha_e_9d307f_idx'),
        ),
    ]
