# Generated by Django 5.1.7 on 2025-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_asistencias_asistencia_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
