# Generated by Django 5.1.7 on 2025-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_asistencia_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='puntos_acumulados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=255),
        ),
    ]
