# Generated by Django 5.1.7 on 2025-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_asistencia_puntos_acumulados_alter_asistencia_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
