# Generated by Django 5.1.7 on 2025-07-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del día (ej: 'Día 1 - Torneo Wolves')", max_length=100)),
                ('fecha', models.DateField(help_text='Fecha del evento', unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta fecha está activa para registrar asistencias')),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='home.fecha'),
        ),
    ]
