# Generated by Django 5.1.7 on 2025-07-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fecha_asistencia_fecha_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='registration_order',
            field=models.IntegerField(default=0),
        ),
    ]
