# Generated by Django 5.1.7 on 2025-07-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_asistencia_registration_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
