# Generated by Django 5.1.7 on 2025-07-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='registration_order',
        ),
    ]
