# Generated by Django 5.1.7 on 2025-07-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_asistencia_registration_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_evento',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(help_text='Fecha y hora de registro'),
        ),
    ]
