# Generated by Django 5.1.7 on 2025-07-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_asistencia_fecha_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('artista', models.CharField(max_length=255)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
