# Generated by Django 5.1.7 on 2025-07-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.CharField(max_length=255),
        ),
    ]
